<?php
// +----------------------------------------------------------------------
// | 应用设置
// +----------------------------------------------------------------------

return [
    // 文章表
    'article_table' => [
        'id',//id
        'md5',//唯一md5
        'title',
        'uid',
        'typeid',
        'content',
        'thumb',
        'tag',
        'create_time',
        'update_time',
        'delete_time',
        'status',
        'click',
        'collection',
        'likes'
    ],
    'article_cate_table' => [
        'id',//id
        'name',//唯一md5
        'create_time',
        'update_time',
        'delete_time',
        'status',
        'click',
        'collection',
        'likes'
    ],
    'shopnav' => [
        'id',
        'sid',
        'name',
        'path',
        'thumb',
        'status',
        'create_time',
        'update_time',
        'delete_time',
    ],'shopad' => [
        'id',
        'sid',
        'name',
        'bg',
        'path',
        'pic',
        'status',
        'create_time',
        'update_time',
        'delete_time',
    ],'goods' => [
      'id',
      'title',
        'keyword',
        'type_id',
        'brand_id',
        'image',
        'price',
        'cbj',
        'yj',
        'sj',
        'goods_unit',
        'cost_price',
        'original_price',
        'sales',
        'content',
        'stock',
        'weight',
        'stock_forewarn',
        'status',
        'likes',
        'collects',
        'comments',
        'create_time',
        'flag'
    ],
    'user_table' => [
        'id',
        'role',
        'phone',
        'unionid',
        'openid',
        'passwd',
        'nickname',
        'avatar',
        'shengfenzheng',
        'fans_num',
        'follows_num',
        'province',
        'city',
        'region',
        'town',
        'village',
        'introduction',
        'create_time',
        'update_time',
        'delete_time',
        'status',
        'sex',
        'freeze_reason',
        'login_num'
    ],
    'scenic_table'=>[
        'id',
        'topic_name',
        'address',
        'addressName',
        'thumb',
        'cover_image',
        'bg_image',
        'description',
        'area',
        'ifshow',
        'status',
        'images',
        'likes',
        'post_count',
        'user_count',
        'create_time',
        'update_time',
    ],
    'scenic_info_table'=>[
      'id',
        'uid',
        'topic_id',
        'discuss_id',
        'vote_id',
        'title',
        'content',
        'media',
        'read_count',
        'post_top',
        'type',
        'status',
        'address',
        'longitude',
        'latitude',
        'create_time',
        'comment_count',
        'fabulous_count',
        'collection_count',
        'is_collection',
        'comment_list',
    ],
    'goods_table' => [
        'id',
        'title',
        'price',
        'attr_status',
        'stock',
        'type_id',
        'uid',
        'gid',
        'goods_unit',
        'thumb',
        'image',
        'cbj',
        'sj',
        'yj',
        'content',
        'create_time',
        'update_time',
        'stock_locked',
        'status',
        'atype',
        'uid',
        'thumb'
    ],'goodsGroup_table' => [
        'id',
        'uid',
        'title',
        'descript',
        'content',
        'clicks',
        'likes',
        'goods',
        'status',
        'create_time',
        'update_time',
    ],'pay_table' => [
        'id',
        'uid',
        'type',
        'gid',
        'oid',
        'sid',
        'status',
        'content',
        'price',
        'create_time',
        'update_time',
    ],'rentCart_table' => [
        'id',
        'uid',
        'cartinfo',
        'create_time',
        'update_time',
        'status',
    ],'html_table' => [
        'id',
        'filename',
        'path',
        'status',
        'create_time',
    ],
    'say' => 'hello',
    'if_buy' => false,
    'if_buylist' => false,
    'if_say' => true,
    'if_say_notice'=> '童年需要家长的用心陪伴.',
    'fatie_jifen' => 10,
    'huitie_jifen' => 3,
    'if_tip'=> true
];
